# build.yml
parameters:
  - name: imageName
    type: string
  - name: dockerHubServiceConnection
    type: string

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "$(dockerHubServiceConnection)"
      repository: "$(imageName)"
      command: "buildAndPush"
      Dockerfile: "$(Build.SourcesDirectory)/src/Ecoeden.Catalogue.Api/Dockerfile" # Path to your Dockerfile
      buildContext: "$(Build.SourcesDirectory)/src/" # Set build context to the root of your repository
      tags: |
        $(Build.BuildId)
