version: '3.4'

services:
  # mongodb:
  #   image: mongo
  
  # mongoexpress:
  #   image: mongo-express

  ecoeden.catalogue.api:
    image: ${DOCKER_REGISTRY-}ecoedencatalogueapi
    build:
      context: .
      dockerfile: ./Ecoeden.Catalogue.Api/Dockerfile

# volumes:
#   mongo_data:
  
# networks:
#   ecoeden_dev_net:
#     external: true
