version: '3.4'

services:
  catalogueDb:
    image: mongo
    container_name: catalogueDb
    ports:
     - 27017:27017
    volumes:
     - catalogueDb_data:/data/db
    networks:
     - ecoeden_dev_net

  mongoexpress:
    container_name: mongoexpress
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=yonce
      - ME_CONFIG_MONGODB_SERVER=catalogueDb
    depends_on:
      - catalogueDb
    networks:
     - ecoeden_dev_net

  ecoeden.catalogue.api:
    container_name: ecoeden.catalogue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Logging__IncludeScopes=false
      - "Logging__LogOutputTemplate=[{Timestamp:dd-MM-yyyy HH:mm:ss, fff}] {Level} {Properties} [CorrelationId:{CorrelationId}] [Machine: {MachineName}] {CallerType}:{MemberName} {Message}{NewLine}{Exception}{NewLine}"
      - Logging__Console__Enabled=true
      - Logging__Console__LogLevel=Debug
      - Logging__Elastic__Enabled=true
      - Logging__Elastic__LogLevel=Debug
      - AppConfigurations__ApplicationIdentifier=Ecoeden.User.Api
      - AppConfigurations__ApplicationEnvironment=docker
      - AppConfigurations__HealthCheckTimeOutInSeconds=2
      - AppConfigurations__CacheExpiration=60
      - AppConfigurations__CategoryCacheKey=category_cache
      - AppConfigurations__ProductCacheKey=product_cache
      - ApiDescription=Catalogue api description
      - ApiOriginHost=localhost:5001
      - IdentityGroupAccess__Authority=http://Ecoeden.IdentityServer 
      - IdentityGroupAccess__Audience=ecoeden.user.api
      - Elasticsearch__Uri=http://elasticsearch:9200
      - ConnectionStrings__Redis=redis:6379
      - "ConnectionStrings__Sqlserver=Server=sqlserver;Database=EcoedenEvent;User Id=sa;Password=P@ssw0rd;Encrypt=True;TrustServerCertificate=True;"
      - Redis__InstanceName=Ecoeden.Catalogue.Cache
      - MongoDb__ConnectionString=mongodb://catalogueDb:27017
      - MongoDb__Database=CatalogueDb
      - EventBus__Host=rabbitmq
      - EventBus__Username=guest
      - EventBus__Password=guest 
    ports:
      - "5002:8080"
    depends_on:
      - catalogueDb
    networks:
     - ecoeden_dev_net